name: CI (Backends)

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    strategy:
      matrix:
        backend: [tensorflow, torch, jax]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install package and backend
        run: |
          pip install -e .
          if [ "${{ matrix.backend }}" = "tensorflow" ]; then
            pip install .[tf]
          elif [ "${{ matrix.backend }}" = "torch" ]; then
            pip install .[torch]
          elif [ "${{ matrix.backend }}" = "jax" ]; then
            pip install .[jax]
          fi

      - name: Run tests
        env:
          KERAS_BACKEND: ${{ matrix.backend }}
        run: pytest -q tests

